// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TushGptBackend.Data;

#nullable disable

namespace TushGptBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317100401_AddInstitutionNameToMembership")]
    partial class AddInstitutionNameToMembership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TushGptBackend.Models.CibilReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CibilScore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawJsonResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReportOrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("cibil_reports", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.MembershipApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aadhaar")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "aadhaar");

                    b.Property<string>("AccInitialAmount")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "acc_initial_amount");

                    b.Property<string>("AccInitialAmountWords")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "acc_initial_amount_words");

                    b.Property<string>("AccType")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "acc_type");

                    b.Property<string>("Age")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "age");

                    b.Property<string>("Branch")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "branch");

                    b.Property<string>("ClientId")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "current_address");

                    b.Property<string>("Date")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "dob");

                    b.Property<bool>("DocAadharCard")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_aadhar_card");

                    b.Property<bool>("DocIdCard")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_id_card");

                    b.Property<bool>("DocLightBill")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_light_bill");

                    b.Property<bool>("DocPanCard")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_pan_card");

                    b.Property<bool>("DocPhotos")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_photos");

                    b.Property<bool>("DocRationCard")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_ration_card");

                    b.Property<bool>("DocResidenceCert")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_residence_cert");

                    b.Property<bool>("DocUtara")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_utara");

                    b.Property<bool>("DocVoterCard")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "doc_voter_card");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FeeEntrance")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fee_entrance");

                    b.Property<string>("FeeOther")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fee_other");

                    b.Property<string>("FeeSavings")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fee_savings");

                    b.Property<string>("FeeShare")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fee_share");

                    b.Property<string>("FeeTotal")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fee_total");

                    b.Property<string>("FeeWelfare")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fee_welfare");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "full_name");

                    b.Property<string>("Holder2Age")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "holder2_age");

                    b.Property<string>("Holder2Name")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "holder2_name");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "institution_name");

                    b.Property<string>("IsMemberElsewhere")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "is_member_elsewhere");

                    b.Property<string>("MembershipNo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "membership_no");

                    b.Property<string>("Mobile")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "mobile");

                    b.Property<string>("MonthlyIncome")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "monthly_income");

                    b.Property<string>("NiNo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "ni_no");

                    b.Property<string>("NomineeAddress")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nominee_address");

                    b.Property<string>("NomineeAge")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nominee_age");

                    b.Property<string>("NomineeDob")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nominee_dob");

                    b.Property<string>("NomineeName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nominee_name");

                    b.Property<string>("NomineeRelation")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nominee_relation");

                    b.Property<string>("OfficialMobile")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "official_mobile");

                    b.Property<string>("OtherExtBranch")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "other_ext_branch");

                    b.Property<string>("OtherExtOrgName")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "other_ext_org_name");

                    b.Property<string>("OtherInstructions")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "other_instructions");

                    b.Property<string>("Pan")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "pan");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "permanent_address");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "photo");

                    b.Property<string>("Recommender1Name")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "recommender1_name");

                    b.Property<string>("Recommender1No")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "recommender1_no");

                    b.Property<string>("Recommender2Name")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "recommender2_name");

                    b.Property<string>("Recommender2No")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "recommender2_no");

                    b.Property<string>("SavingAccNo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "saving_acc_no");

                    b.Property<string>("WorkingAddress")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "working_address");

                    b.Property<string>("YearlyIncome")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "yearly_income");

                    b.HasKey("Id");

                    b.ToTable("membership_applications", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("otp_code");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsVerified");

                    b.ToTable("otp_verifications", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AppId");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DataJson");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReportDate");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MemberName");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.InstallmentPayee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountHolderNameAtBank")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name_at_bank");

                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_number");

                    b.Property<string>("AmountCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("amount_currency");

                    b.Property<double>("AmountValue")
                        .HasColumnType("double")
                        .HasColumnName("amount_value");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("branch_name");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ifsc");

                    b.Property<string>("InstallmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("installment_id");

                    b.Property<string>("InstrumentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.Property<string>("Vpa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("vpa");

                    b.HasKey("Id");

                    b.HasIndex("InstallmentId");

                    b.ToTable("installment_payees");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.InstallmentPayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountHolderNameAtBank")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name_at_bank");

                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_number");

                    b.Property<string>("AmountCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("amount_currency");

                    b.Property<double>("AmountValue")
                        .HasColumnType("double")
                        .HasColumnName("amount_value");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("branch_name");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ifsc");

                    b.Property<string>("InstallmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("installment_id");

                    b.Property<string>("InstrumentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.Property<string>("Vpa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("vpa");

                    b.HasKey("Id");

                    b.HasIndex("InstallmentId")
                        .IsUnique();

                    b.ToTable("installment_payers");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.InstallmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenericError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("generic_error");

                    b.Property<string>("InstallmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("installment_id");

                    b.Property<string>("Medium")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medium");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("SubState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sub_state");

                    b.Property<string>("SubStateReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sub_state_reason");

                    b.Property<string>("SubStateTimestamp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sub_state_timestamp");

                    b.Property<long?>("TxnCreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("txn_created_at");

                    b.Property<string>("TxnId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("txn_id");

                    b.Property<string>("Umrn")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("umrn");

                    b.Property<string>("Utr")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("utr");

                    b.HasKey("Id");

                    b.HasIndex("InstallmentId");

                    b.ToTable("installment_transactions");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.MandatePayee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountHolderNameAtBank")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name_at_bank");

                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_number");

                    b.Property<string>("AmountCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("amount_currency");

                    b.Property<double>("AmountValue")
                        .HasColumnType("double")
                        .HasColumnName("amount_value");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("branch_name");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ifsc");

                    b.Property<string>("InstrumentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mandate_id");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex("MandateId");

                    b.ToTable("mandate_payees");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.MandatePayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountHolderNameAtBank")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("account_holder_name_at_bank");

                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_number");

                    b.Property<string>("AmountCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("amount_currency");

                    b.Property<double>("AmountValue")
                        .HasColumnType("double")
                        .HasColumnName("amount_value");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("branch_name");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ifsc");

                    b.Property<string>("InstrumentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mandate_id");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex("MandateId")
                        .IsUnique();

                    b.ToTable("mandate_payers");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.MandateTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GatewayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gateway_name");

                    b.Property<string>("GatewayReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("gateway_reference_id");

                    b.Property<string>("GenericError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("generic_error");

                    b.Property<string>("MandateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mandate_id");

                    b.Property<string>("Medium")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medium");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("SubState")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sub_state");

                    b.Property<long?>("TxnCreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("txn_created_at");

                    b.Property<string>("TxnId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("txn_id");

                    b.Property<string>("Umrn")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("umrn");

                    b.Property<string>("Utr")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("utr");

                    b.HasKey("Id");

                    b.HasIndex("MandateId");

                    b.ToTable("mandate_transactions");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.RocketPayInstallment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<string>("ClientMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("client_meta_description");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deleted");

                    b.Property<string>("DueDate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("local_created_at");

                    b.Property<DateTime>("LocalUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("local_updated_at");

                    b.Property<string>("MandateId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mandate_id");

                    b.Property<string>("MmsId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mms_id");

                    b.Property<string>("PaymentOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payment_order_id");

                    b.Property<string>("RawJson")
                        .HasColumnType("longtext")
                        .HasColumnName("raw_json");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_type");

                    b.Property<string>("ScheduleDate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("schedule_date");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("time_zone");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("rocketpay_installments");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.RocketPayMandate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<double>("AdvanceAmount")
                        .HasColumnType("double")
                        .HasColumnName("advance_amount");

                    b.Property<double>("ApprovalAmount")
                        .HasColumnType("double")
                        .HasColumnName("approval_amount");

                    b.Property<string>("ClientMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("client_meta_description");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deleted");

                    b.Property<string>("EndDate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("end_date");

                    b.Property<string>("EnterpriseHandlerEntity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("enterprise_handler_entity");

                    b.Property<string>("EnterpriseId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("frequency");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("int")
                        .HasColumnName("installment_count");

                    b.Property<DateTime>("LocalCreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("local_created_at");

                    b.Property<DateTime>("LocalUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("local_updated_at");

                    b.Property<string>("MandateAuthCheckoutUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mandate_auth_checkout_url");

                    b.Property<string>("MmsId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mms_id");

                    b.Property<string>("PaymentOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payment_order_id");

                    b.Property<string>("RawJson")
                        .HasColumnType("longtext")
                        .HasColumnName("raw_json");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_type");

                    b.Property<string>("StartDate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("time_zone");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("rocketpay_mandates");
                });

            modelBuilder.Entity("TushGptBackend.Models.User", b =>
                {
                    b.Property<int?>("UserCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserCode");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("UserCode"));

                    b.Property<string>("UserLoginId")
                        .HasColumnType("longtext")
                        .HasColumnName("UserLoginId");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPwd")
                        .HasColumnType("longtext")
                        .HasColumnName("UserPwd");

                    b.HasKey("UserCode");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.VerifiedAadhar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("VerifiedAt");

                    b.ToTable("verified_aadhars", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.InstallmentPayee", b =>
                {
                    b.HasOne("TushGptBackend.Models.RocketPay.RocketPayInstallment", "Installment")
                        .WithMany("Payees")
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.InstallmentPayer", b =>
                {
                    b.HasOne("TushGptBackend.Models.RocketPay.RocketPayInstallment", "Installment")
                        .WithOne("Payer")
                        .HasForeignKey("TushGptBackend.Models.RocketPay.InstallmentPayer", "InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.InstallmentTransaction", b =>
                {
                    b.HasOne("TushGptBackend.Models.RocketPay.RocketPayInstallment", "Installment")
                        .WithMany("Transactions")
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.MandatePayee", b =>
                {
                    b.HasOne("TushGptBackend.Models.RocketPay.RocketPayMandate", "Mandate")
                        .WithMany("Payees")
                        .HasForeignKey("MandateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandate");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.MandatePayer", b =>
                {
                    b.HasOne("TushGptBackend.Models.RocketPay.RocketPayMandate", "Mandate")
                        .WithOne("Payer")
                        .HasForeignKey("TushGptBackend.Models.RocketPay.MandatePayer", "MandateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandate");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.MandateTransaction", b =>
                {
                    b.HasOne("TushGptBackend.Models.RocketPay.RocketPayMandate", "Mandate")
                        .WithMany("Transactions")
                        .HasForeignKey("MandateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandate");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.RocketPayInstallment", b =>
                {
                    b.Navigation("Payees");

                    b.Navigation("Payer");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TushGptBackend.Models.RocketPay.RocketPayMandate", b =>
                {
                    b.Navigation("Payees");

                    b.Navigation("Payer");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
