// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TushGptBackend.Data;

#nullable disable

namespace TushGptBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226104233_AddReportsTable")]
    partial class AddReportsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TushGptBackend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AppId");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DataJson");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ReportDate");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MemberName");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("TushGptBackend.Models.User", b =>
                {
                    b.Property<int?>("UserCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserCode");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("UserCode"));

                    b.Property<string>("UserLoginId")
                        .HasColumnType("longtext")
                        .HasColumnName("UserLoginId");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPwd")
                        .HasColumnType("longtext")
                        .HasColumnName("UserPwd");

                    b.HasKey("UserCode");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
